### ISSUE TITLE
Covering cljc/clj files and macros in the examples would be useful

### ISSUE THREAD

**Issue by infracanophile** [thheller/shadow-build-example#1]
In trying to figure out how shadow-build, macros, and code reloading works I've got a fork of this repo that I re-arranged a bit and added some macros: https://github.com/infracanophile/shadow-build-example

For cljc files everything seems to work as expected but the plain clj file macro namespace wasn't being found during compilation unless I require'd it in the dev.build namespace myself.

This isn't really an issue for me (I only added the clj macros file for completeness) but it makes me think that I'm not understanding how to properly use shadow-build.

**Comment by thheller** [comment]
You got is almost all correct. The problem you are experiencing is actually not related to shadow-build at all. Here is what is happening:

shadow-build tries to compile `demo.app`, it does `(:require demo.extras)`, this in turn does this:

```clojure
(ns demo.extras
  #?(:cljs (:require-macros demo.extras
                            demo.macros
                            )))
```

The CLJS part looks like:
```clojure
(ns demo.extras
  (:require-macros demo.extras
                   demo.macros))
```

while the CLJ part looks like ```(ns demo.extras)```. `shadow-build` sees the `:refer-macros` and attempts to load the `demo.extras` CLJ part. Now when Clojure is attempting to compile `demo.extras`, it encounters

```clojure
(defn clojure-file-make-tuple [x y]
  (demo.macros/clojure-file-list-macro x y))
```

The CLJ part does not know `demo.macros` and blows up.

The fix is simple:

```clojure
(ns demo.extras
  #?(:cljs (:require-macros demo.extras
                            demo.macros)
     :clj (:require [demo.macros])))
```

CLJC files make for some really confusing errors sometimes. I will check why the error message is so bad and try to improve that. Somewhat confused that this error is not caught.


Try to avoid using fully qualified names whenever possible. :)

**Comment by infracanophile** [comment]
Ah, of course. That's an embarrassing mistake for someone who does a *lot* of cljc!

So far shadow-build is working out quite wonderfully btw, thanks for all the work you've put into it.

**Comment by thheller** [comment]
Glad to hear it.

If you have any questions just ask, happy to help.
